travis:
  secure:
    BINSTAR_TOKEN: gS2TzoL1NwMY5Qb3fQ2jMSu5Q9mFubvUrPh5CsnxLA4scwJWAwY6i2sUi6NcSCnozH/TU3cik1SAhm3ar1d42+nu2ejztO+evy3Y7TUbETC/whTdReS9BAzpVsk+uZDBLgQftJs2w/p+zbGBRUNquPjt9ZfV3w8wc65xY403vB9TtzjiUCG8e3EgZd3HeuWOiNTfkgofpagkjeuTMNr5xcPTEn1ZKIho5hUTI+T/UcONKsPvsr9r6lrNNsqHA7K624iagKS6PgxHzQ95IBGuNitES52YHPjQTio9yCxaBnlWcpxOFHPXYTcF+Us+Nh1x12BfsVp5rZaNq8WBLGaqUsystwqg3NzHeI7aAVtiuEDM7BI/H0dRaALm3jfPk35jxPotfy3pM+5QVBg9soHvXSeQSdnnN0JW9lU/mwztCGv/UoDe4cs80G/D0s4+cSvkoI7OumDZ6gqMIbjTn5pZtO3kwVwaLYwkLElgfh6Tg8AB8+lYkjKzjkNSiM5HFc3gKTF8G+rQqzGBgcTSPe+ntvBYRdJlDqzwwr7UEc7OFR0SoAGLlCj6n6Tz+2M6OE5baUmAPdv6bD+qNV1HjkbjfZm66HDhsVw/GVcQxwi1ji498TTQYTv/qY0Fk5Lokhouyn3ejAhLujYP3OHqP3Exx8tRSnqCwJdE4EiEt+HdYg0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
