travis:
  secure:
    BINSTAR_TOKEN: HXr3uCuD3wR2jbUTZGYwP6NzVtI16IJ+JWYM0xoPTauKNWhZoSvQjepUDfSaHPL6d+e8NUxlYDHhh1LKGwV7TjQ/ftrNTWJD+DtaNRhDTWKp4l6aYgvfbRfmm5Hrkv4rgVOvZLTHn0Z7rw3xqDJAbWRkWN6s50MI+nWavzIAUsXHh/zjZ80GOQ/0PZSGS2AWN93dInTULZhxe7nyQdMgxVf9Gs1iOlLS3iEXtkgpYJmmj2vDE1QbzjGCQ8vU0jQ1SsaSwEK+TCjRDGtV5FKvuDBb20f3ItJOc1FaCpAyGpk9X7Fwonv2KMwL7mqL/PSaDiOk1+XVLYpmBmxhJfpUA6QMMMg0qK1FZ5l+UZzmzxyrG2zIz5U/lRvXXG5ZM16fOK4YeYWzswTJNOMBPMuRlWpiQbGX/Udzl07n4DU5OHOKOB3nhr5uB3KyNz2LllL6hBhO0bEYsafWnG/S8w4qy4Z/XI1ikCBxVcNoZuFF6bcEF1rrH5M90qnb5J+E7HIDGL9LOOmzRafidfOYRUlF8UvTkp57BMlxK5JAlp3XA/GoP4f2b+bPw+sSwkYoXP9Kg88s2Bi5Qbyg/wnvfXkVGsPUz+QEVferGmP1wpNVZ8Dv9cLp6KUW5+BdoCcSpMxn9HexMkZtA3qDeIzs7EYlBzYwqqnJZcJzVcUgDANFcgw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
